name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: cargo publish
        run: |
          cargo publish -p ocipkg
          cargo publish -p ocipkg-cli
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  next_version:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump version
        run: |
          cargo set-version --bump patch
          echo "NEW_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Start developing ${{ env.NEW_VERSION }}"
          branch: "rust-version-update/${{ env.NEW_VERSION }}"
          base: "main"
